[package]
name = "pkg"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version = '0.11.2', features = ['vendored', 'lua54', 'async', 'send'] }
kdl = "6.3.4"
miette = { version = "7.6.0", features = ["fancy"] }
thiserror = "2.0.15"
